### ISSUE TITLE
actividad 3. operaciones

### ISSUE THREAD

**Issue by Proyect-A16** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Proyect-A16#1]
[Actividad 3. operaciones.pdf](https://github.com/user-attachments/files/16847462/Actividad.3.operaciones.pdf)

**Comment by LeinnaMora** [comment]
Portada: 25/25
Procedimiento: 20/25
Figuras, Ilustraciones y Fotografías: 10/25
Resultados y Conclusiones: 20/25
Calificación Final: 15/20

**Comment by josealfredo79** [comment]
Revisado..
